### ISSUE TITLE
Apply to Y Combinator

### ISSUE THREAD

**Issue by MarwanRefaat** [MarwanRefaat/transcend#11]
# Overview
Apply to Y Combinator startup accelerator for potential to raise $500K

## Tasks
- [ ] Add main application questions to markdown document
- [ ] Add personal/team profile questions to markdown document
- [ ] Record application video
- [ ] Request recommendations from YC alums who can vouch for us
