### ISSUE TITLE
Create Transcend accounts on music distribution platform

### ISSUE THREAD

**Issue by MarwanRefaat** [MarwanRefaat/transcend#8]
# Overview
[BeatStars](https://beatstars.com) and [DistroKid](https://distrokid.com) distribute songs across all major music streamers (Spotify, Apple Music, Tik Tok etc.) the goal here is to create an account on those two platforms and determine which is best to use for Transcend

## Tasks
- [x] Create and test [BeatStars](https://beatstars.com) account
- [x] Create and test [DistroKid](https://distrokid.com) account
- [ ] Create and test [TuneCore](https://tunecore.com) account

## Verdict (TuneCore still not tested)
After reviewing both platforms it seems like BeatStars is the better choice given it's a more modern and intuitive platform with a richer feature set at a very similar price point, the one major disadvantage with BeatStars however is that it is not currently possible to manage multiple artists under one account in the same way you can with DistroKid so Transcend will need to internally create and manage individual artist accounts who are invited as collaborators.
